--维修厂
DROP TABLE  IF EXISTS dwd_graphbase.ENTERPRISE_ENTITY_REPAIRFACTORY;
CREATE  TABLE dwd_graphbase.ENTERPRISE_ENTITY_REPAIRFACTORY AS 
SELECT  
  T.REGISTNO ,--"报案号",
  T1.REPAIRTYPECODE  ENTERPRISE_KIND_CODE,--"修理厂类型代码", 1 2 3 
  T1.REPAIRTYPENAME ENTERPRISE_KIND_NAME,--"修理厂类型名称", 一类修理厂 二类修理厂
  T1.REPAIRFACTORYCODE ENTERPRISE_CODE ,-- "修理厂代码", TP0660001111
  T1.REPAIRFACTORYNAME ENTERPRISE_NAME ,--"修理厂名称", xxx别克4s店
  '' AS ENTERPRISE_LEVEL,--企业等级
  '' AS PHONE,
  'ENTERPRISE_OF_REPAIRFACTORY' KIND --修理厂种类 
  ,T.ETL_DATE 
  ,"太财" COMPANY
 ,T3.COMPANYCODE	--机构代码
 FROM dwd_graphbase.filter_gcregistitem T
LEFT OUTER JOIN dwd_graphbase.filter_gcregistitemEXT T1 ON T.REGISTNO = T1.REGISTNO AND T.LOSSID = T1.LOSSID
  LEFT JOIN 
 dwd_graphbase.filter_gcclaimmain T3
ON  T.REGISTNO=T3.REGISTNO
;


--医院。案件涉及人伤的被保人治疗医院(和被保人关联，确定是人伤对应的被保人额度治疗医院)

DROP TABLE  IF EXISTS dwd_graphbase.ENTERPRISE_ENTITY_HOAPITAL;
CREATE  TABLE dwd_graphbase.ENTERPRISE_ENTITY_HOAPITAL AS 
SELECT  
  T.REPORT_CODE REGISTNO --"报案号"
  ,T1.HOSPITAL_TYPE ENTERPRISE_KIND_CODE --"医院类型" 01 04 06 
  ,'' AS ENTERPRISE_KIND_NAME --医院类型名称
  ,T1.HOSPITAL_CODE ENTERPRISE_CODE --"医院代码" 670776-0001 
  ,T1.HOSPITAL_NAME ENTERPRISE_NAME  --"医院名称" 江密市人名医院
  ,T1.HOSPITAL_LEVEL ENTERPRISE_LEVEL --"医院等级" 企业等级 06 00 09 
  --,T1.ORGANIZATION_CODE  --"组织机构代码" L22790000
  ,T1.HOSPITAL_PHONE  PHONE  --"企业电话" 0461-66622671
  ,'HOSPITAL' KIND --医院种类 
  ,T.ETL_DATE 
    ,"太财" COMPANY
 ,T4.COMPANYCODE	--机构代码
  FROM dwd_graphbase.filter_mc_flow T 
    LEFT JOIN 
 dwd_graphbase.filter_gcclaimmain T4
 ON T.REPORT_CODE=T4.REGISTNO
 LEFT OUTER JOIN dwd_graphbase.filter_mc_hospital T1 ON T.ID = T1.FLOW_ID AND T1.DEL_FLAG='0'
 LEFT OUTER JOIN  dwd_graphbase.filter_mc_survey T2 ON T.ID = T2.FLOW_ID
 INNER JOIN  dwd_graphbase.filter_gupolicyriskRELATEDPARTY T3 
 ON T3.INSUREDNAME=T.INJURE_NAME AND T3.IDENTIFYTYPE=T2.INJURE_CERTIFICATE_TYPE_CODE AND T3.IDENTIFYNUMBER=T2.INJURE_CERTIFICATE_CODE
 WHERE T3.INSUREDFLAG <> '4'
 AND T1.IN_HOSPITAL_DATE is not null
;



--企业对应的投保人

--TMP_POLICYNO_APPLI AS (

DROP TABLE  IF EXISTS dwd_graphbase.ENTERPRISE_ENTITY_POLICYNO_APPLI;
CREATE  TABLE dwd_graphbase.ENTERPRISE_ENTITY_POLICYNO_APPLI AS 
  SELECT 
 -- T.POLICYNO,
  T3.REGISTNO REGISTNO,-- "报案号",
  --T1.RISKCODE "险种",
  --T2.INSUREDCODE "投保人代码",
  '' AS ENTERPRISE_KIND_NAME,
  T2.INSUREDNAME ENTERPRISE_NAME ,--"投保人姓名",
  T2.IDENTIFYTYPE ENTERPRISE_KIND_CODE ,--"投保人证件类型",
  T2.IDENTIFYNUMBER ENTERPRISE_CODE ,--"投保人证件号",
  '' AS ENTERPRISE_LEVEL,
  T2.MOBILEPHONE  PHONE ,--"投保人电话",
  'EP_APPLI' KIND  --人员类型
  ,T.ETL_DATE 
    ,"太财" COMPANY
 ,T.COMPANYCODE	--机构代码
  FROM dwd_graphbase.filter_gupolicymain T 
INNER JOIN dwd_graphbase.filter_gupolicyrisk T1 ON T.POLICYNO = T1.POLICYNO
LEFT OUTER JOIN dwd_graphbase.filter_gupolicyrelatedparty T2 ON T.POLICYNO = T2.POLICYNO AND T2.INSUREDFLAG='1'
LEFT OUTER JOIN dwd_graphbase.filter_gcclaimmain  T3 ON T.POLICYNO = T3.POLICYNO
WHERE 1=1
 AND T.INSUREDCODE IN (
  SELECT DISTINCT T.CLIENTCODE FROM dwd_graphbase.filter_gsclientcorporate T
  )
;

--企业对应的被保人
--TMP_POLICYNO_INSURED AS (   
DROP TABLE  IF EXISTS dwd_graphbase.ENTERPRISE_ENTITY_POLICYNO_INSURED;
CREATE  TABLE dwd_graphbase.ENTERPRISE_ENTITY_POLICYNO_INSURED AS 
  SELECT 
  T.REGISTNO, 
 -- T.POLICYNO,
  '' AS ENTERPRISE_KIND_NAME,
  T.INSUREDNAME ENTERPRISE_NAME , --被保人姓名
  T.IDENTIFYTYPE  ENTERPRISE_KIND_CODE, --被保人身份证类型
  T.IDENTIFYNUMBER  ENTERPRISE_CODE, --被保人身份证号吗
  '' AS ENTERPRISE_LEVEL, 
   T.INSUREDMOBILEPHONE PHONE, --被保人电话
  'EP_INSURED' KIND --被保人种类
  ,T.ETL_DATE 
  ,T.COMPANY
  ,T.COMPANYCODE
   FROM (
   SELECT  
     T3.REGISTNO,
     T.POLICYNO,
     T.RISKCODE,
     T.INSUREDNAME,
     T.IDENTIFYTYPE,
     T.IDENTIFYNUMBER,
     T.INSUREDMOBILEPHONE,
     T.ETL_DATE
	 ,"太财" COMPANY
 ,T3.COMPANYCODE	--机构代码
  FROM dwd_graphbase.filter_gupolicyriskRELATEDPARTY T
  LEFT OUTER JOIN dwd_graphbase.filter_gcclaimmain  T3 ON T.POLICYNO = T3.POLICYNO
WHERE 1=1
   AND T.INSUREDFLAG <> '4'
   AND T.INSUREDCODE IN (
   SELECT DISTINCT T.CLIENTCODE FROM dwd_graphbase.filter_gsclientcorporate T
   )
   ) T
  -- WHERE T.POLICYNO='67111080120160051115'
;

--公估机构
DROP TABLE  IF EXISTS dwd_graphbase.ENTERPRISE_ENTITY_ASSESSMENT;
CREATE  TABLE dwd_graphbase.ENTERPRISE_ENTITY_ASSESSMENT AS 
SELECT 
T2.REGISTNO --报案号码
,'05' AS ENTERPRISE_KIND_CODE --企业类型代码
,T1.PAYEE AS ENTERPRISE_KIND_NAME --企业类型名称
,T1.CERTICODE AS ENTERPRISE_CODE --企业代码
,T1.PAYEEBANKACCOUNTNAME AS ENTERPRISE_NAME --企业名称
,''  AS ENTERPRISE_LEVEL --企业等级
,T1.PAYEEMOBILE AS PHONE --企业电话
, 'ENTERPRISE_OF_ASSESSMENT' AS KIND --种类
,T1.ETL_DATE  
,T1.PAYEE --公估机构名称
,T1.CLAIMNO --立案号码
,T1.POLICYNO --保单号码
,T1.RISKCODE --险种代码
	 ,"太财" COMPANY
 ,T2.COMPANYCODE	--机构代码

FROM 
DWD_GRAPHBASE.FILTER_GCADJUSTMENTFEE T1 --赔付金额汇总表
LEFT JOIN 
DWD_GRAPHBASE.FILTER_GCCLAIMMAIN T2    --立案主表
ON T1.CLAIMNO=T2.CLAIMNO 
AND T1.RISKCODE=T2.RISKCODE
WHERE 
T1.CHARGECODE="05" --
AND T2.CLAIMIND='1' --案件是否有效
;


--企业对应的车主：

DROP TABLE  IF EXISTS dwd_graphbase.ENTERPRISE_ENTITY_OWNER_VEHICLE;
CREATE  TABLE dwd_graphbase.ENTERPRISE_ENTITY_OWNER_VEHICLE AS 
SELECT 
 T4.REGISTNO --报案号码
,'' AS ENTERPRISE_KIND_NAME
,T1.CAROWNER ENTERPRISE_NAME  --车辆行驶证车主
,T1.IDENTIFYTYPE ENTERPRISE_KIND_CODE  --证件类型代码
,T1.IDENTIFYNUMBER ENTERPRISE_CODE --证件号码
,'' AS ENTERPRISE_LEVEL
,T1.PHONENUMBER  PHONE--联系电话
, 'ENTERPRISE_OF_VEHICLE_OWN'  AS KIND
,T.ETL_DATE 
,"太财" COMPANY
 ,T4.COMPANYCODE	--机构代码
FROM DWD_GRAPHBASE.FILTER_GUPOLICYRISK T
INNER JOIN DWD_GRAPHBASE.FILTER_GUPOLICYVEHICLEOWNER T1 --太财保单车主信息
 ON T.SUBPOLICYNO = T1.SUBPOLICYNO --分保单号
INNER JOIN DWD_GRAPHBASE.FILTER_GUPOLICYITEMMOTOR T2  --太财车险保单标的信息
ON T.POLICYNO=T2.POLICYNO --保单号码
LEFT JOIN 
DWD_GRAPHBASE.FILTER_GUPOLICYRELATEDPARTY T3
ON 
 T2.POLICYNO = T3.POLICYNO AND T3.INSUREDFLAG='1'
LEFT JOIN 
DWD_GRAPHBASE.FILTER_GCCLAIMMAIN T4    --立案主表
ON T.POLICYNO=T4.POLICYNO 
AND T.RISKCODE=T4.RISKCODE
WHERE T3.INSUREDTYPE ='2'
;


--银行账号对应的企业： 从银行账号实体中取值
DROP TABLE  IF EXISTS dwd_graphbase.ENTERPRISE_ENTITY_ACCOUNT_E;
CREATE  TABLE dwd_graphbase.ENTERPRISE_ENTITY_ACCOUNT_E AS 
SELECT
 T1.POLICYNO
,T1.payeename USERNAME
,T1.identifytypeall IDENTIFYTYPE
,T1.IDENTIFYNUMBER
,T2.MOBILEPHONE TEL
,'ACCOUNT_OF_ENTERPRISE_OWN' AS KIND 
,T2.ETL_DATE
,T1.COMPANY
,T1.COMPANYCODE
FROM 
DWD_GRAPHBASE.ACCOUNT_PAY_TMP1 T1
INNER JOIN 
DWD_GRAPHBASE.FILTER_GUPOLICYRELATEDPARTY T2 ON T1.POLICYNO = T2.POLICYNO 
WHERE 1=1
 AND T2.INSUREDCODE  IN (
  SELECT DISTINCT T.CLIENTCODE FROM dwd_graphbase.filter_gsclientcorporate T
  )
;




DROP TABLE  IF EXISTS dwd_graphbase.ENTERPRISE_ENTITY_UNION;
CREATE  TABLE dwd_graphbase.ENTERPRISE_ENTITY_UNION AS 
select 
 CONCAT('E','00000000',ENTERPRISE_CODE) ENTERPRISEID
,REGISTNO
,ENTERPRISE_KIND_NAME
,ENTERPRISE_NAME
,ENTERPRISE_KIND_CODE
,ENTERPRISE_CODE
,ENTERPRISE_LEVEL
,PHONE
,KIND
,ETL_DATE 
,COMPANY
,COMPANYCODE
from 
dwd_graphbase.ENTERPRISE_ENTITY_REPAIRFACTORY
UNION ALL
SELECT 
 CONCAT('E','00000000',ENTERPRISE_CODE) ENTERPRISEID
,REGISTNO
,ENTERPRISE_KIND_NAME
,ENTERPRISE_NAME
,ENTERPRISE_KIND_CODE
,ENTERPRISE_CODE
,ENTERPRISE_LEVEL
,PHONE
,KIND
,ETL_DATE 
,COMPANY
,COMPANYCODE
FROM 
dwd_graphbase.ENTERPRISE_ENTITY_HOAPITAL
UNION ALL 
SELECT 
 CONCAT('E','00000000',NVL(ENTERPRISE_NAME,''),NVL(ENTERPRISE_KIND_CODE,''),NVL(ENTERPRISE_CODE,'')) ENTERPRISEID
,REGISTNO
,ENTERPRISE_KIND_NAME
,ENTERPRISE_NAME
,ENTERPRISE_KIND_CODE
,ENTERPRISE_CODE
,ENTERPRISE_LEVEL
,PHONE
,KIND
,ETL_DATE 
,COMPANY
,COMPANYCODE
FROM 
dwd_graphbase.ENTERPRISE_ENTITY_POLICYNO_APPLI
UNION ALL
SELECT 
 CONCAT('E','00000000',NVL(ENTERPRISE_NAME,''),NVL(ENTERPRISE_KIND_CODE,''),NVL(ENTERPRISE_CODE,'')) ENTERPRISEID
,REGISTNO
,ENTERPRISE_KIND_NAME
,ENTERPRISE_NAME
,ENTERPRISE_KIND_CODE
,ENTERPRISE_CODE
,ENTERPRISE_LEVEL
,PHONE
,KIND
,ETL_DATE 
,COMPANY
,COMPANYCODE
FROM 
dwd_graphbase.ENTERPRISE_ENTITY_POLICYNO_INSURED
UNION ALL
SELECT 
 CONCAT('E','00000000',NVL(ENTERPRISE_NAME,'未知'),NVL(ENTERPRISE_KIND_CODE,'未知'),NVL(ENTERPRISE_CODE,'未知')) ENTERPRISEID
,REGISTNO
,ENTERPRISE_KIND_NAME
,ENTERPRISE_NAME
,ENTERPRISE_KIND_CODE
,ENTERPRISE_CODE
,ENTERPRISE_LEVEL
,PHONE
,KIND
,ETL_DATE
,COMPANY
,COMPANYCODE
FROM 
dwd_graphbase.ENTERPRISE_ENTITY_ASSESSMENT
UNION ALL
SELECT 
 CONCAT('E','00000000',ENTERPRISE_NAME,ENTERPRISE_KIND_CODE,ENTERPRISE_CODE) ENTERPRISEID
,REGISTNO
,ENTERPRISE_KIND_NAME
,ENTERPRISE_NAME
,ENTERPRISE_KIND_CODE
,ENTERPRISE_CODE
,ENTERPRISE_LEVEL
,PHONE
,KIND
,ETL_DATE
 ,COMPANY
,COMPANYCODE
FROM 
dwd_graphbase.ENTERPRISE_ENTITY_OWNER_VEHICLE
;



--DROP TABLE  IF EXISTS DWD_GRAPHBASE.ENTERPRISE_ENTITY;
--INSERT OVERWRITE TABLE DWD_GRAPHBASE.ENTERPRISE_ENTITY
DROP TABLE  IF EXISTS dwd_graphbase.ENTERPRISE_ENTITY;
CREATE  TABLE dwd_graphbase.ENTERPRISE_ENTITY AS 
SELECT DISTINCT
 T.ENTERPRISEID
,T.REGISTNO
,T.ENTERPRISE_KIND_NAME
,T.ENTERPRISE_NAME
,T.ENTERPRISE_KIND_CODE
,T.ENTERPRISE_CODE
,T.ENTERPRISE_LEVEL
,T.PHONE
,T.KIND
,T.ETL_DATE 
,COMPANY
,COMPANYCODE
,'' as ENTERPRISE_LAST_MARKER
,'' AS ENTERPRISE_MARKED_STATUS
,'' AS ENTERPRISE_MARKED_TAG
,'1990-01-01  00:00:00' AS ENTERPRISE_LAST_MARKED_TIME
FROM 
DWD_GRAPHBASE.ENTERPRISE_ENTITY_UNION T;




-- 修理厂，医院，企业投保人和被保人 UNION




